### ISSUE TITLE
README

### ISSUE THREAD

**Issue by erikkartmen** [t3ran13/golos-msg-shopot#1]
В README, стоит указать более подробно по поводу ключей memo, так как несведующий не сразу поймёт что к чему, а, и более подробно расписать по установке на локальную машинку!
P.S. Если, конечно же, будет решение оставить такую замечательную РЕАЛИЗОВАННУЮ фичу, давным-давно заложенную в код БЧ!!!

**Comment by erikkartmen** [comment]
Да, и почему бы не сделать кнопку "запомнить меня", что бы каждый раз не вводить ключи?

**Comment by t3ran13** [comment]
по ключам вопрос безопасности хранения, и вопрос удобства) нужно думать)

**Comment by erikkartmen** [comment]
А чего фон убрал? Вроде бы красивый был)))

**Comment by t3ran13** [comment]
Это просто картинка, а нужно именно для фона чтото подыскать)
